// Code generated by a template
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using PclSharp.Std;
namespace PclSharp.Common
{

	public static partial class Invoke
	{
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void transforms_transformPointCloud(IntPtr cloud_in,IntPtr cloud_out,IntPtr transform, [MarshalAs(UnmanagedType.I1)] bool copy_all_fields);
	}

	public  class Transforms 
	{
		public static void TransformPointCloud(PointCloudOfXYZ cloud_in,ref PointCloudOfXYZ cloud_out,Eigen.Matrix4f transform,bool copy_all_fields=false)
		{
			Invoke.transforms_transformPointCloud(cloud_in.Ptr,cloud_out.Ptr,transform.Ptr,copy_all_fields);
		}
	}
}
