// Code generated by a template
#pragma once
#include "..\export.h"
#include <pcl/io/ply_io.h>
#include <pcl/point_types.h>

using namespace pcl;
using namespace std;

#ifdef __cplusplus
extern "C" {
#endif

EXPORT(PLYReader*) io_plyreader_ctor()
{
	return new PLYReader();
}

EXPORT(void) io_plyreader_delete(PLYReader** ptr)
{
	delete *ptr;
	*ptr = NULL;
}

EXPORT(int32_t) io_plyreader_read_xyz(PLYReader* ptr, const char* str, PointCloud<PointXYZ>* cloud, int offset)
{
	return ptr->read(string(str), *cloud, offset);
}
EXPORT(int32_t) io_plyreader_read_xyzrgba(PLYReader* ptr, const char* str, PointCloud<PointXYZRGBA>* cloud, int offset)
{ return ptr->read(string(str), *cloud, offset); }


#ifdef __cplusplus  
}
#endif
