
// Code generated by a template
using PclSharp.Std;
using PclSharp.Search;
namespace PclSharp.Filters
{
	public abstract class BilateralFilter<PointT> : Filter<PointT>
	{
		public abstract double HalfSize { get; set; }
		public abstract double StdDev { get; set; }
		public abstract double ComputePointWeight(int pid,VectorOfInt indices,VectorOfFloat distance);
		public abstract void SetSearchMethod(KdTree<PointT>  tree);
		
	}
}
