// Code generated by a template
using PclSharp.Std;
using PclSharp.Search;
namespace PclSharp.Filters
{
	public abstract class FastBilateralFilter<PointT> : Filter<PointT>
	{
	    public abstract float SigmaS { get; set; }
		public abstract float SigmaR { get; set; }
	}
}
