// Code generated by a template
using System;
using System.Collections.Generic;
using System.Numerics;
using System.Runtime.InteropServices;
using PclSharp.Struct;
using PclSharp.Std;
using PclSharp.Search;
namespace PclSharp.Filters
{
	public static partial class Invoke
	{
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern IntPtr filters_fastBilateralFilter_xyz_ctor();
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void filters_fastBilateralFilter_xyz_delete(ref IntPtr ptr);
		//methods
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void filters_fastBilateralFilter_xyz_filter(IntPtr ptr, IntPtr output);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void filters_fastBilateralFilter_xyz_setInputCloud(IntPtr ptr, IntPtr cloud);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void filters_fastBilateralFilter_xyz_setIndices(IntPtr ptr, IntPtr indices);


		//properties
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void filters_fastBilateralFilter_xyz_setSigmaS(IntPtr ptr, float value);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern float filters_fastBilateralFilter_xyz_getSigmaS(IntPtr ptr);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void filters_fastBilateralFilter_xyz_setSigmaR(IntPtr ptr, float value);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern float filters_fastBilateralFilter_xyz_getSigmaR(IntPtr ptr);
	}

	public class FastBilateralFilterOfXYZ : FastBilateralFilter<PointXYZ>
	{
		public override float SigmaS
		{
			get { return Invoke.filters_fastBilateralFilter_xyz_getSigmaS(_ptr); }
            set { Invoke.filters_fastBilateralFilter_xyz_setSigmaS(_ptr, value); }
		}

		public override float SigmaR
		{
			get { return Invoke.filters_fastBilateralFilter_xyz_getSigmaR(_ptr); }
            set { Invoke.filters_fastBilateralFilter_xyz_setSigmaR(_ptr, value); }
		}


		public FastBilateralFilterOfXYZ()
		{
			_ptr = Invoke.filters_fastBilateralFilter_xyz_ctor();
		}

		public override void SetInputCloud(PointCloud<PointXYZ> cloud)
		{
			Invoke.filters_fastBilateralFilter_xyz_setInputCloud(_ptr, cloud);
		}

		public override void filter(PointCloud<PointXYZ> output)
		{
			Invoke.filters_fastBilateralFilter_xyz_filter(_ptr, output.Ptr);
		}

		public override void SetIndices(VectorOfInt indices)
		{
			Invoke.filters_fastBilateralFilter_xyz_setIndices(_ptr, indices);
		}

		public override ref PointXYZ this[int idx]
		{
			get { return ref this.Index(idx); }
		}

		protected override void DisposeObject()
		{
			Invoke.filters_fastBilateralFilter_xyz_delete(ref _ptr);
		}
	}
}
