// Code generated by a template
namespace PclSharp.Filters
{
	public abstract class PassThrough<PointT> : FilterIndices<PointT>
	{
		public abstract void  SetFilterFieldName(string filterFieldName);
		public abstract string  GetFilterFieldName();
		public abstract bool FilterLimitsNegative { get; set; }
		public abstract void SetFilterLimits(float limit_min,float limit_max);
		public abstract void GetFilterLimits(ref float limit_min,ref float limit_max);
	}
}
