// Code generated by a template
namespace PclSharp.Filters
{
	public abstract class RadiusOutlierRemoval<PointT> : FilterIndices<PointT>
	{
		public abstract double RadiusSearch { get; set; }
		public abstract int MinNeighborsInRadius { get; set; }
	}
}
