// Code generated by a template
#pragma once
#include "..\export.h"
#include <pcl/common/transforms.h>

using namespace pcl;
using namespace std;

#ifdef __cplusplus
extern "C" {
#endif


EXPORT(void) transforms_transformPointCloud(const PointCloud<PointXYZ> &cloud_in,PointCloud<PointXYZ> &cloud_out,const Eigen::Matrix4f &transform,bool copy_all_fields)
{
	pcl::transformPointCloud(cloud_in,cloud_out,transform,copy_all_fields);
}

#ifdef __cplusplus  
}
#endif
