// Code generated by a template
#pragma once
#include "..\export.h"

#include "pcl\pcl_base.h"
#include "pcl\point_types.h"
#include <pcl/filters/grid_minimum.h>

using namespace pcl;
using namespace std;

typedef GridMinimum<PointXYZ> filter_t;
typedef boost::shared_ptr<PointCloud<PointXYZ>> boost_cloud;

#ifdef __cplusplus
extern "C" {
#endif 

EXPORT(filter_t*) filters_gridMinimum_xyz_ctor(float resolution)
{
	return new filter_t(resolution);
}

EXPORT(void) filters_gridMinimum_xyz_delete(filter_t** ptr)
{
	delete *ptr;
	*ptr = NULL;
}

EXPORT(void) filters_gridMinimum_xyz_filter(GridMinimum<PointXYZ>* ptr, PointCloud<PointXYZ>* output)
{
	ptr->filter(*output);
}

EXPORT(void) filters_gridMinimum_xyz_setInputCloud(GridMinimum<PointXYZ>* ptr, PointCloud<PointXYZ>* cloud)
{
	ptr->setInputCloud(boost_cloud(boost_cloud(), cloud));
}

EXPORT(void) filters_gridMinimum_xyz_setIndices(GridMinimum<PointXYZ>* ptr, vector<int>* indices)
{
	ptr->setIndices(boost::shared_ptr<vector<int>>(boost::shared_ptr<vector<int>>(), indices));
}

EXPORT(void) filters_gridMinimum_xyz_setResolution(GridMinimum<PointXYZ>* ptr, float value)
{ ptr->setResolution(value); }
EXPORT(float) filters_gridMinimum_xyz_getResolution(GridMinimum<PointXYZ>* ptr)
{ return ptr->getResolution(); }

EXPORT(void) filters_gridMinimum_xyz_setKeepOrganized(GridMinimum<PointXYZ>* ptr, int value)
{ ptr->setKeepOrganized(value); }
EXPORT(int) filters_gridMinimum_xyz_getKeepOrganized(GridMinimum<PointXYZ>* ptr)
{ return ptr->getKeepOrganized(); }

EXPORT(void) filters_gridMinimum_xyz_setNegative(GridMinimum<PointXYZ>* ptr, int value)
{ ptr->setNegative(value); }
EXPORT(int) filters_gridMinimum_xyz_getNegative(GridMinimum<PointXYZ>* ptr)
{ return ptr->getNegative(); }

#ifdef __cplusplus  
}
#endif  
