// Code generated by a template
#pragma once
#include "..\export.h"

#include "pcl\pcl_base.h"
#include "pcl\point_types.h"
#include <pcl/filters/radius_outlier_removal.h>

using namespace pcl;
using namespace std;

typedef RadiusOutlierRemoval<PointXYZ> filter_t;
typedef boost::shared_ptr<PointCloud<PointXYZ>> boost_cloud;

#ifdef __cplusplus
extern "C" {
#endif 

EXPORT(filter_t*) filters_radiusOutlierRemoval_xyz_ctor(bool extractRemovedIndices)
{
	return new filter_t(extractRemovedIndices);
}

EXPORT(void) filters_radiusOutlierRemoval_xyz_delete(filter_t** ptr)
{
	delete *ptr;
	*ptr = NULL;
}

EXPORT(void) filters_radiusOutlierRemoval_xyz_filter(RadiusOutlierRemoval<PointXYZ>* ptr, PointCloud<PointXYZ>* output)
{
	ptr->filter(*output);
}

EXPORT(void) filters_radiusOutlierRemoval_xyz_setInputCloud(RadiusOutlierRemoval<PointXYZ>* ptr, PointCloud<PointXYZ>* cloud)
{
	ptr->setInputCloud(boost_cloud(boost_cloud(), cloud));
}

EXPORT(void) filters_radiusOutlierRemoval_xyz_setIndices(RadiusOutlierRemoval<PointXYZ>* ptr, vector<int>* indices)
{
	ptr->setIndices(boost::shared_ptr<vector<int>>(boost::shared_ptr<vector<int>>(), indices));
}

EXPORT(void) filters_radiusOutlierRemoval_xyz_setRadiusSearch(RadiusOutlierRemoval<PointXYZ>* ptr, double value)
{ ptr->setRadiusSearch(value); }
EXPORT(double) filters_radiusOutlierRemoval_xyz_getRadiusSearch(RadiusOutlierRemoval<PointXYZ>* ptr)
{ return ptr->getRadiusSearch(); }

EXPORT(void) filters_radiusOutlierRemoval_xyz_setMinNeighborsInRadius(RadiusOutlierRemoval<PointXYZ>* ptr, int value)
{ ptr->setMinNeighborsInRadius(value); }
EXPORT(int) filters_radiusOutlierRemoval_xyz_getMinNeighborsInRadius(RadiusOutlierRemoval<PointXYZ>* ptr)
{ return ptr->getMinNeighborsInRadius(); }

EXPORT(void) filters_radiusOutlierRemoval_xyz_setKeepOrganized(RadiusOutlierRemoval<PointXYZ>* ptr, int value)
{ ptr->setKeepOrganized(value); }
EXPORT(int) filters_radiusOutlierRemoval_xyz_getKeepOrganized(RadiusOutlierRemoval<PointXYZ>* ptr)
{ return ptr->getKeepOrganized(); }

EXPORT(void) filters_radiusOutlierRemoval_xyz_setNegative(RadiusOutlierRemoval<PointXYZ>* ptr, int value)
{ ptr->setNegative(value); }
EXPORT(int) filters_radiusOutlierRemoval_xyz_getNegative(RadiusOutlierRemoval<PointXYZ>* ptr)
{ return ptr->getNegative(); }

#ifdef __cplusplus  
}
#endif  
