// Code generated by a template
using System;
using System.Collections.Generic;
using System.Numerics;
using System.Runtime.InteropServices;
using PclSharp.Struct;
using PclSharp.Std;
namespace PclSharp.IO
{
	public static partial class Invoke
	{
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern IntPtr io_plywriter_ctor();
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void io_plywriter_delete(ref IntPtr ptr);

		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern int io_plywriter_write_xyz(IntPtr ptr, string fileName, IntPtr cloud, int offset);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern int io_plywriter_write_xyzrgba(IntPtr ptr, string fileName, IntPtr cloud, int offset);
	}

	public class PLYWriter : UnmanagedObject
	{
		public PLYWriter()
		{
			_ptr = Invoke.io_plywriter_ctor();
		}

		public int Write(string fileName, PointCloud<PointXYZ> cloud, int indices=0)
		{
			var res = Invoke.io_plywriter_write_xyz(_ptr, fileName, cloud.Ptr, indices);
			return res;
		}

		public int Write(string fileName, PointCloud<PointXYZRGBA> cloud, int indices=0)
		{
			return Invoke.io_plywriter_write_xyzrgba(_ptr, fileName, cloud, indices);
		}

		protected override void DisposeObject()
		{
			Invoke.io_plywriter_delete(ref _ptr);
		}
	}
}
